### ISSUE TITLE
Intergrating GPS_interpolation jupyter notebnook

### ISSUE THREAD

**Issue by webgisdeveloper** [GeoGateway/geogateway-django-app#192]
make a demo first,

**Comment by webgisdeveloper** [comment]
[sample call](https://archive.geo-gateway.org/gpsservice/kml?function=getinterpolation&lat=32.97180377635759&lon=-115.55419921875001&width=1.4503504753021161&height=1.0691460280633294&epoch=&epoch1=2010-04-01&epoch2=2011-04-01&scale=&ref=&ct=&pt=&dwin1=&dwin2=&prefix=&mon=false&eon=&vabs=&analysisCenter=)

return
>"""{"urlprefix": "https://archive.geo-gateway.org/static/", "folder": "kml062820222101222137", "results": ["contour_of_LOS_Displacement_colorbar.png", "contour_of_Delta_E.png", "contour_of_LOS_Displacement.png", "displacement_horizontal.kml", "contour_of_Delta_E_colorbar.png", "contour_of_Delta_V.png", "gps_interpolation.zip", "displacement_table.txt", "contour_of_Delta_N_colorbar.png", "displacement_vertical.kml", "contour_of_Delta_V_colorbar.png", "contour_of_Delta_N.png"], "urls": ["https://archive.geo-gateway.org/static/kml062820222101222137/contour_of_LOS_Displacement_colorbar.png", "https://archive.geo-gateway.org/static/kml062820222101222137/contour_of_Delta_E.png", "https://archive.geo-gateway.org/static/kml062820222101222137/contour_of_LOS_Displacement.png", "https://archive.geo-gateway.org/static/kml062820222101222137/displacement_horizontal.kml", "https://archive.geo-gateway.org/static/kml062820222101222137/contour_of_Delta_E_colorbar.png", "https://archive.geo-gateway.org/static/kml062820222101222137/contour_of_Delta_V.png", "https://archive.geo-gateway.org/static/kml062820222101222137/gps_interpolation.zip", "https://archive.geo-gateway.org/static/kml062820222101222137/displacement_table.txt", "https://archive.geo-gateway.org/static/kml062820222101222137/contour_of_Delta_N_colorbar.png", "https://archive.geo-gateway.org/static/kml062820222101222137/displacement_vertical.kml", "https://archive.geo-gateway.org/static/kml062820222101222137/contour_of_Delta_V_colorbar.png", "https://archive.geo-gateway.org/static/kml062820222101222137/contour_of_Delta_N.png"], "imagebounds": [[32.616527, -116.183077], [33.423873, -115.031805]]} """

**Comment by webgisdeveloper** [comment]
two more issues: 
* display color bar   
* four parameters

**Comment by webgisdeveloper** [comment]
need work on the legend: https://codepen.io/haakseth/pen/KQbjdO
```javascript
/*Legend specific*/
var legend = L.control({ position: "bottomright" });

legend.onAdd = function (map) {
  var div = L.DomUtil.create("div", "legend");
  div.innerHTML += "<h4>LOS_Displacement</h4>";
  div.innerHTML +=
    "<img src=https://archive.geo-gateway.org/static/kml259320220809040858/contour_of_LOS_Displacement_colorbar.png />";
  return div;
};

legend.addTo(map);
```
```css
/*Legend specific*/
.legend {
  padding: 6px 8px;
  font: 14px Arial, Helvetica, sans-serif;
  background: rgba(255, 255, 255, 0.6);
  box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
  border-radius: 5px;
  line-height: 24px;
  color: #555;
}
.legend h4 {
  text-align: center;
  font-size: 16px;
  margin: 2px 12px 8px;
  color: #777;
}

.legend span {
  position: relative;
  bottom: 3px;
}

.legend i {
  width: 18px;
  height: 18px;
  float: left;
  margin: 0 8px 0 0;
  opacity: 0.7;
}

.legend i.icon {
  background-size: 18px;
  background-color: rgba(255, 255, 255, 1);
}
```

![GNSS_legend](https://user-images.githubusercontent.com/6643873/153121574-1e3507fb-12b3-45f7-b43c-2b8fd71806b5.JPG)
